version: 1.0.{build}

branches:
  only:
    - master

skip_commits:
  files:
  - LICENCE
  - '**/*.md'
  - samples/**/*

configuration: Release
platform: Any CPU

before_build:
  - appveyor-retry dotnet restore src/Bartender -v Minimal
  - appveyor-retry dotnet restore test/Bartender.Tests -v Minimal
  
build_script:
  - dotnet build src/Bartender --version-suffix %APPVEYOR_BUILD_NUMBER%
  - dotnet build test/Bartender.Tests --version-suffix %APPVEYOR_BUILD_NUMBER%
  
after_build:
  - dotnet pack src/Bartender --version-suffix %APPVEYOR_BUILD_NUMBER% --no-build -o artifacts
  
test_script:
  - dotnet test test/Bartender.Tests
  
artifacts:
  - path: artifacts\**\*.*
  
deploy:
  - provider: NuGet
    api_key:
      secure: VMmYNhMOvK7DxZOKna0yOYRLtBWqyuBQSPD08mRIz70v9G//tAVOBbk+voQmltnJ
    artifact: /.*\.nupkg/
    skip_symbols: true
