version: 1.0.{build}

branches:
  only:
    - master

skip_commits:
  files:
  - LICENCE
  - '**/*.md'

configuration: Release
platform: Any CPU

before_build:
  - appveyor-retry dotnet restore src/Bartender -v Minimal
  - appveyor-retry dotnet restore test/Bartender.Tests -v Minimal
  
build_script:
  - dotnet build src/Bartender
  - dotnet build test/Bartender.Tests
  
after_build:
  - dotnet pack src/Bartender -o artifacts
  
test_script:
  - dotnet test test/Bartender.Tests
  
artifacts:
  - path: artifacts\**\*.*
