version: 1.0.{build}

branches:
  only:
    - master

configuration: Release

test: off

build:
      project: Cheers.Cqrs\Cheers.Cqrs.csproj
      verbosity: minimal

artifacts:
  path: Cheers.Cqrs\bin\$(configuration)
  name: Cheers.Cqrs
