version: 1.0.{build}

branches:
  only:
    - master

configuration: Release

test: on

before_build:
  - nuget restore

build:
      project: Cheers.ServiceLocator\Cheers.ServiceLocator.csproj
      verbosity: minimal

artifacts:
  path: Cheers.ServiceLocator\bin\$(configuration)
  name: Cheers.ServiceLocator
