version: 1.0.{build}

branches:
  only:
    - master

configuration: Release

test: off

build:
      project: Cheers.Cqrs\Cheers.Cqrs.csproj
#      publish_nuget: true
#      include_nuget_references: true
      verbosity: minimal
	  
#deploy:
#  - provider: NuGet
#    api_key:
#      secure: LVu+nQKMjKgF50fFDcSYCo4RPSUm+Z6LYcJwJF1z9n/3L6eZaSnmYWQLxPL00ymd
#    artifact: /.*\.nupkg/
	
artifacts:
  path: Cheers.Cqrs\bin\$(configuration)
  name: Cheers.Cqrs