version: 1.0.{build}

branches:
  only:
    - master

configuration: Release

test:
  assemblies:
    - '**\*.tests.dll'

before_build:
  - nuget restore

build:
      project: Cheers.Cqrs.InMemory\Cheers.Cqrs.InMemory.csproj
      verbosity: minimal

artifacts:
  path: Cheers.Cqrs.InMemory\bin\$(configuration)
  name: Cheers.Cqrs.InMemory
